name = "killerinstinct"
main = "src/index.ts"
compatibility_date = "2024-07-22"

account_id = "d5b60342409ec10347cc15a90a01bf03"
workers_dev = false

[[r2_buckets]]
binding = 'cc-fetch' 
bucket_name = 'killerinstinct-bucket01'
